server:
  port: 8060

spring:
  ######## redis configuration #######
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    lettuce:
      pool:
        max-idle: 9
        min-idle: 1
        max-active: 9
        max-wait: 5000
        
  ######## freemarker configuration #######
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl